In [2]:
# Data Visualization
# BTech Computer Science Stream
# Week 3: Numpy basics and vectorized computation
# Kenneth Francis Rodrigues, 240905112, 3/1/2025

In [3]:
import numpy as np

In [4]:
# Problem 1
# 1. Generate a 3x4 NumPy array with random integers between 1 
# and 50.   
# a. Calculate and print the Mean, Median, and Standard Deviation 
# of the array 
# b. Print the Sum of all elements and the sum of each row. 
# c. Reshape the 3x4 array into a 2x6 array and print it. 

arr = np.random.randint(1,50,(3,4))
print('Array:\n',arr)
print('mean: ',np.mean(arr))
print('median: ',np.median(arr))
print('standard deviation: ',np.std(arr))
print('sum of all elements: ',np.sum(arr))
print('row-wise sum: ',np.sum(arr,axis=1))
arr = np.reshape(arr,(2,6))
print('After reshaping:')
print(arr)

Array:
 [[45  1 43 12]
 [22 43 38 46]
 [45 15 48  6]]
mean:  30.333333333333332
median:  40.5
standard deviation:  16.98201663198128
sum of all elements:  364
row-wise sum:  [101 149 114]
After reshaping:
[[45  1 43 12 22 43]
 [38 46 45 15 48  6]]


In [5]:
# Problem 2
# 2. Create two (3 * 3) matrices using NumPy and print it. Perform 
# and print the results of the following linear algebra operations 
# a. Matrix addition 
# b. Matrix subtraction 
# c. Matrix multiplication (element-wise and dot product) 
# d. Transpose of a matrix 
# e. Determinant and inverse (if applicable) 

arr1 = np.random.randint(0,100,(3,3))
arr2 = np.random.randint(0,100,(3,3))
print('Array 1: \n',arr1)
print('Array 2: \n',arr2)

arradd = arr1 + arr2
print('After Adding:\n',arradd)

arrsub = arr1 - arr2
print('After Subtracting:\n',arrsub)

arrmul = np.dot(arr1,arr2)
print('After Multiplication:\n',arrmul)

print('Array 1 Transpose:\n',arr1.T)
print('Array 2 Transpose:\n',arr2.T)

det1 = np.linalg.det(arr1)
det2 = np.linalg.det(arr2)

print('Determinant of array 1: ',det1)
print('Determinant of array 2: ',det2)

if det1 != 0:
    inv1 = np.linalg.inv(arr1)
    print('Inverse of array 1:\n',inv1)
    
if det2 != 0:
    inv2 = np.linalg.inv(arr2)
    print('Inverse of array 1:\n',inv2)

Array 1: 
 [[29 43 55]
 [29 17  2]
 [57  4 17]]
Array 2: 
 [[17 13 59]
 [ 8 27 90]
 [84 24 42]]
After Adding:
 [[ 46  56 114]
 [ 37  44  92]
 [141  28  59]]
After Subtracting:
 [[ 12  30  -4]
 [ 21 -10 -88]
 [-27 -20 -25]]
After Multiplication:
 [[5457 2858 7891]
 [ 797  884 3325]
 [2429 1257 4437]]
Array 1 Transpose:
 [[29 29 57]
 [43 17  4]
 [55  2 17]]
Array 2 Transpose:
 [[17  8 84]
 [13 27 24]
 [59 90 42]]
Determinant of array 1:  -55063.000000000065
Determinant of array 2:  -46013.99999999999
Inverse of array 1:
 [[-0.00510325  0.00928028  0.0154187 ]
 [ 0.00688302  0.0479814  -0.02791348]
 [ 0.01549135 -0.04240597  0.01369341]]
Inverse of array 1:
 [[ 0.02229756 -0.01890729  0.00919285]
 [-0.1569957   0.09218933  0.022993  ]
 [ 0.0451167  -0.01486504 -0.00771504]]


In [8]:
def magic_check(mat):
    nums_used = []
    for i in range(len(mat)):
        for j in range(len(mat)):
            if mat[i][j] not in nums_used:
                nums_used.append(a[i][j])
            else:
                return False
    rowsums = [sum(x) for x in mat]
    for i in range(1,len(rowsums)):
        if rowsums[i] != rowsums[0]:
            return False
    colsums = [0]*len(mat)
    for i in range(len(mat)):
        for j in range(len(mat)):
            colsums[j] += mat[i][j]
    for i in range(1,len(colsums)):
        if colsums[i] != colsums[0]:
            return False
    if colsums[0]!=rowsums[0]:
        return False
    diagsum1 = 0
    diagsum2 = 0
    for i in range(len(mat)):
        diagsum1 += mat[i][i]
        diagsum2 += mat[i][len(mat)-i-1]
    if diagsum1 != diagsum2:
        return False
    if diagsum1 != rowsums[0]:
        return False
    return True

In [9]:
a = [[9,2,7],[4,6,8],[5,10,3]]
print(magic_check(a))

True
