In [1]:
# Data Visualization
# BTech Computer Science Stream
# Week 4: pandas
# Kenneth Francis Rodrigues, 240905112, 3/1/2025

In [2]:
import numpy as np
import pandas as pd

In [4]:
obj= pd.Series(np.arange(4.),index=['a','b','c','d'])
print(obj)
print(obj['b'])
print(obj[1])
print(obj[2:4])
print(obj[['b','a','d']])
print(obj[[1,3]])
obj[obj<2]

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64
1.0
1.0
c    2.0
d    3.0
dtype: float64
b    1.0
a    0.0
d    3.0
dtype: float64
b    1.0
d    3.0
dtype: float64


a    0.0
b    1.0
dtype: float64

In [5]:
obj.loc[['b','a','d']]

b    1.0
a    0.0
d    3.0
dtype: float64

In [6]:
obj1 = pd.Series([1, 2, 3], index=[2, 0, 1])
obj2 = pd.Series([1, 2, 3], index=["a", "b", "c"])
print(obj1)
print(obj2)
print(obj1[[0, 1, 2]])
print(obj2[[0, 1, 2]])

2    1
0    2
1    3
dtype: int64
a    1
b    2
c    3
dtype: int64
0    2
1    3
2    1
dtype: int64
a    1
b    2
c    3
dtype: int64


In [7]:
print(obj1.iloc[[0, 1, 2]])
obj2.iloc[[0, 1, 2]]

2    1
0    2
1    3
dtype: int64


a    1
b    2
c    3
dtype: int64

In [8]:
obj2.loc['b':'c']

b    2
c    3
dtype: int64

In [9]:
obj2.loc["b":"c"] = 5
obj2

a    1
b    5
c    5
dtype: int64

In [10]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=["Ohio", "Colorado", "Utah", "New York"],
                    columns=["one", "two", "three", "four"])
print(data)
print(data["two"])
print(data[["three", "one"]])

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15
Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int32
          three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12


In [11]:
print(data[:2])
data[data["three"] > 5]

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7


one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [12]:
data < 5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [13]:
data[data < 5] = 0
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [14]:
data.loc["Colorado"]

one      0
two      5
three    6
four     7
Name: Colorado, dtype: int32

In [15]:
data.loc[["Colorado", "New York"]]

one  two  three  four
Colorado    0    5      6     7
New York   12   13     14    15

In [16]:
data.loc["Colorado", ["two", "three"]]

two      5
three    6
Name: Colorado, dtype: int32

In [17]:
print(data.iloc[2])
print(data.iloc[[2, 1]])
print(data.iloc[2, [3, 0, 1]])
print(data.iloc[[1, 2], [3, 0, 1]])

one       8
two       9
three    10
four     11
Name: Utah, dtype: int32
          one  two  three  four
Utah        8    9     10    11
Colorado    0    5      6     7
four    11
one      8
two      9
Name: Utah, dtype: int32
          four  one  two
Colorado     7    0    5
Utah        11    8    9


In [18]:
print(data.loc[:"Utah", "two"])
data.iloc[:, :3][data.three > 5]

Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int32


one  two  three
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

In [19]:
data.loc[data.three >= 2]

one  two  three  four
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [33]:
ser = pd.Series(np.arange(3.))
print(ser)
ser[-1:]

0    0.0
1    1.0
2    2.0
dtype: float64


1    1.0
2    2.0
dtype: float64

In [37]:
ser2 = pd.Series(np.arange(3.),index=['a','b','c'])
print(ser2[-1:])
print(ser.iloc[-1:])
print(ser[:2])

c    2.0
dtype: float64
2    2.0
dtype: float64
0    0.0
1    1.0
dtype: float64


In [25]:
data.loc[:, "one"] = 1
data

one  two  three  four
Ohio        1    0      0     0
Colorado    1    5      6     7
Utah        1    9     10    11
New York    1   13     14    15

In [27]:
 data.iloc[2] = 5
data

one  two  three  four
Ohio        1    0      0     0
Colorado    1    5      6     7
Utah        5    5      5     5
New York    1   13     14    15

In [28]:
 data.loc[data["four"] > 5] = 3
data    

one  two  three  four
Ohio        1    0      0     0
Colorado    3    3      3     3
Utah        5    5      5     5
New York    3    3      3     3

In [34]:
data.loc[data.three == 5, "three"] = 6
data

one  two  three  four
Ohio        1    0      0     0
Colorado    3    3      3     3
Utah        5    5      6     5
New York    3    3      3     3

In [38]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=["a", "c", "d", "e"])
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1],index=["a", "c", "e", "f", "g"])
print(s1)
print(s2)
s1+s2

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64
a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64


a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [39]:
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)), columns=list("bcd"),index=["Ohio", "Texas", "Colorado"])
df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list("bde"),index=["Utah", "Ohio", "Texas", "Oregon"])
print(df1)
print(df2)
print(df1+df2)

            b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0
          b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0
            b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN


In [40]:
df1 = pd.DataFrame({"A": [1, 2]})
df2 = pd.DataFrame({"B": [3, 4]})
print(df1)
print(df2)
print(df1+df2)

   A
0  1
1  2
   B
0  3
1  4
    A   B
0 NaN NaN
1 NaN NaN


In [41]:
df1 = pd.DataFrame(np.arange(12.).reshape((3, 4)),columns=list("abcd"))
df2 = pd.DataFrame(np.arange(20.).reshape((4, 5)),columns=list("abcde"))
df2.loc[1,'b'] = np.nan
print(df1)
print(df2)
print(df1+df2)

     a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0
      a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0
      a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN


In [42]:
 df1.add(df2, fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [45]:
print(1 / df1)
print(df1.rdiv(1))
df1.reindex(columns=df2.columns, fill_value=0)

       a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909
       a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909


a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

In [46]:
arr = np.arange(12.).reshape((3, 4))
print(arr)
print(arr[0])
print(arr-arr[0])

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
[0. 1. 2. 3.]
[[0. 0. 0. 0.]
 [4. 4. 4. 4.]
 [8. 8. 8. 8.]]


In [48]:
frame = pd.DataFrame(np.arange(12.).reshape((4, 3)),
                     columns=list("bde"),
                     index=["Utah", "Ohio", "Texas", "Oregon"])
series = frame.iloc[0]
print(frame)
series

          b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0


b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [49]:
frame - series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [50]:
series2 = pd.Series(np.arange(3), index=["b", "e", "f"])
series2

b    0
e    1
f    2
dtype: int32

In [51]:
frame + series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [53]:
series3 = frame["d"]
print(series3)
frame.sub(series3, axis="index")

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64


b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

In [54]:
frame = pd.DataFrame(np.random.standard_normal((4, 3)),
                     columns=list("bde"),
                     index=["Utah", "Ohio", "Texas", "Oregon"])
frame

b         d         e
Utah   -1.394801  1.070671 -0.462216
Ohio    0.275513  1.325725 -0.913181
Texas  -1.154667  0.153875 -0.016308
Oregon -0.249058  0.884393 -1.476523

In [55]:
 np.abs(frame)

b         d         e
Utah    1.394801  1.070671  0.462216
Ohio    0.275513  1.325725  0.913181
Texas   1.154667  0.153875  0.016308
Oregon  0.249058  0.884393  1.476523

In [56]:
 def f1(x):
    return x.max() - x.min()

In [57]:
frame.apply(f1)

b    1.670314
d    1.171850
e    1.460215
dtype: float64

In [58]:
 frame.apply(f1, axis="columns")

Utah      2.465471
Ohio      2.238906
Texas     1.308542
Oregon    2.360916
dtype: float64

In [59]:
def f2(x):
    return pd.Series([x.min(), x.max()], index=["min", "max"])
frame.apply(f2)

b         d         e
min -1.394801  0.153875 -1.476523
max  0.275513  1.325725 -0.016308

In [61]:
def my_format(x):
    return f"{x:.2f}"

In [62]:
 frame.applymap(my_format)

b     d      e
Utah    -1.39  1.07  -0.46
Ohio     0.28  1.33  -0.91
Texas   -1.15  0.15  -0.02
Oregon  -0.25  0.88  -1.48

In [63]:
frame["e"].map(my_format)

Utah      -0.46
Ohio      -0.91
Texas     -0.02
Oregon    -1.48
Name: e, dtype: object

In [64]:
obj = pd.Series(np.arange(4), index=["d", "a", "b", "c"])
print(obj)
obj.sort_index()

d    0
a    1
b    2
c    3
dtype: int32


a    1
b    2
c    3
d    0
dtype: int32

In [65]:
frame = pd.DataFrame(np.arange(8).reshape((2, 4)),
                     index=["three", "one"],
                     columns=["d", "a", "b", "c"])
print(frame)
print(frame.sort_index())
print(frame.sort_index(axis="columns"))
print(frame.sort_index(axis="columns", ascending=False))

       d  a  b  c
three  0  1  2  3
one    4  5  6  7
       d  a  b  c
one    4  5  6  7
three  0  1  2  3
       a  b  c  d
three  1  2  3  0
one    5  6  7  4
       d  c  b  a
three  0  3  2  1
one    4  7  6  5


In [66]:
obj = pd.Series([4, 7, -3, 2])
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

In [67]:
obj = pd.Series([4, np.nan, 7, np.nan, -3, 2])
obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [68]:
obj.sort_values(na_position="first")

1    NaN
3    NaN
4   -3.0
5    2.0
0    4.0
2    7.0
dtype: float64

In [69]:
frame = pd.DataFrame({"b": [4, 7, -3, 2], "a": [0, 1, 0, 1]})
print(frame)
print(frame.sort_values("b"))
print(frame.sort_values(["a", "b"]))

   b  a
0  4  0
1  7  1
2 -3  0
3  2  1
   b  a
2 -3  0
3  2  1
0  4  0
1  7  1
   b  a
2 -3  0
0  4  0
3  2  1
1  7  1


In [70]:
obj = pd.Series([7, -5, 7, 4, 2, 0, 4])
print(obj.rank())
print(obj.rank(method="first"))
print(obj.rank(ascending=False))

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64
0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64
0    1.5
1    7.0
2    1.5
3    3.5
4    5.0
5    6.0
6    3.5
dtype: float64


In [71]:
frame = pd.DataFrame({"b": [4.3, 7, -3, 2], "a": [0, 1, 0, 1],
                      "c": [-2, 5, 8, -2.5]})
print(frame)
frame.rank(axis="columns")

b    a    c
0  3.0  2.0  1.0
1  3.0  1.0  2.0
2  1.0  2.0  3.0
3  3.0  2.0  1.0

In [72]:
obj = pd.Series(np.arange(5), index=["a", "a", "b", "b", "c"])
print(obj)
obj.index.is_unique

a    0
a    1
b    2
b    3
c    4
dtype: int32


False

In [73]:
print(obj["a"])
obj["c"]

a    0
a    1
dtype: int32


4

In [74]:
df = pd.DataFrame(np.random.standard_normal((5, 3)),
                  index=["a", "a", "b", "b", "c"])
print(df)
print(df.loc["b"])
print(df.loc["c"])

          0         1         2
a -0.896498 -0.348730  0.478690
a  0.639755 -0.040185 -0.314674
b -0.565836 -0.498470 -0.389619
b  0.109021 -0.085695 -0.009332
c -0.740856  0.454889 -1.530603
          0         1         2
b -0.565836 -0.498470 -0.389619
b  0.109021 -0.085695 -0.009332
0   -0.740856
1    0.454889
2   -1.530603
Name: c, dtype: float64


In [75]:
df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5],[np.nan, np.nan], [0.75, -1.3]],index=["a", "b", "c", "d"],columns=["one", "two"])
print(df)
print(df.sum())
print(df.sum(axis="columns"))
print(df.sum(axis="index", skipna=False))
print(df.sum(axis="columns", skipna=False))
print(df.mean(axis="columns"))
print(df.idxmax())
print(df.cumsum())
print(df.describe())

    one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3
one    9.25
two   -5.80
dtype: float64
a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64
one   NaN
two   NaN
dtype: float64
a     NaN
b    2.60
c     NaN
d   -0.55
dtype: float64
a    1.400
b    1.300
c      NaN
d   -0.275
dtype: float64
one    b
two    d
dtype: object
    one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8
            one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000


In [76]:
obj = pd.Series(["a", "a", "b", "c"] * 4)
obj.describe()

count     16
unique     3
top        a
freq       8
dtype: object

In [80]:
price = pd.read_pickle("examples/yahoo_price.pkl")
volume = pd.read_pickle("examples/yahoo_volume.pkl")

In [81]:
returns = price.pct_change()
returns.tail()

AAPL      GOOG       IBM      MSFT
Date                                              
2016-10-17 -0.000680  0.001837  0.002072 -0.003483
2016-10-18 -0.000681  0.019616 -0.026168  0.007690
2016-10-19 -0.002979  0.007846  0.003583 -0.002255
2016-10-20 -0.000512 -0.005652  0.001719 -0.004867
2016-10-21 -0.003930  0.003011 -0.012474  0.042096

In [82]:
print(returns["MSFT"].corr(returns["IBM"]))
print(returns["MSFT"].cov(returns["IBM"]))

0.4997636114415114
8.870655479703546e-05


In [83]:
print(returns.corr())
print(returns.cov())

          AAPL      GOOG       IBM      MSFT
AAPL  1.000000  0.407919  0.386817  0.389695
GOOG  0.407919  1.000000  0.405099  0.465919
IBM   0.386817  0.405099  1.000000  0.499764
MSFT  0.389695  0.465919  0.499764  1.000000
          AAPL      GOOG       IBM      MSFT
AAPL  0.000277  0.000107  0.000078  0.000095
GOOG  0.000107  0.000251  0.000078  0.000108
IBM   0.000078  0.000078  0.000146  0.000089
MSFT  0.000095  0.000108  0.000089  0.000215


In [84]:
returns.corrwith(returns["IBM"])

AAPL    0.386817
GOOG    0.405099
IBM     1.000000
MSFT    0.499764
dtype: float64

In [85]:
returns.corrwith(volume)

AAPL   -0.075565
GOOG   -0.007067
IBM    -0.204849
MSFT   -0.092950
dtype: float64

In [86]:
obj = pd.Series(["c", "a", "d", "a", "a", "b", "b", "c", "c"])
uniques = obj.unique()
print(uniques)
print(obj.value_counts())
print(pd.value_counts(obj.to_numpy(), sort=False))

['c' 'a' 'd' 'b']
c    3
a    3
b    2
d    1
dtype: int64
c    3
a    3
d    1
b    2
dtype: int64


In [87]:
mask = obj.isin(["b", "c"])
print(mask)
print(obj[mask])

0     True
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
dtype: bool
0    c
5    b
6    b
7    c
8    c
dtype: object


In [90]:
to_match = pd.Series(["c", "a", "b", "b", "c", "a"])
unique_vals = pd.Series(["c", "b", "a"])
indices =pd.Index(unique_vals).get_indexer(to_match)
indices

array([0, 2, 1, 1, 0, 2], dtype=int64)

In [91]:
data = pd.DataFrame({'Qu1':[1,3,4,3,4],
                    'Qu2':[2,3,1,2,3],
                    'Qu3':[1,5,2,4,4]})
data

Qu1  Qu2  Qu3
0    1    2    1
1    3    3    5
2    4    1    2
3    3    2    4
4    4    3    4

In [92]:
data['Qu1'].value_counts().sort_index()

1    1
3    2
4    2
Name: Qu1, dtype: int64

In [93]:
result =data.apply(pd.value_counts).fillna(0)
result

Qu1  Qu2  Qu3
1  1.0  1.0  1.0
2  0.0  2.0  1.0
3  2.0  2.0  0.0
4  2.0  0.0  2.0
5  0.0  0.0  1.0

In [94]:
data = pd.DataFrame({'a':[1,1,1,2,2],'b':[0,0,1,0,0]})
data
data.value_counts()

a  b
1  0    2
2  0    2
1  1    1
dtype: int64