In [1]:
# Data Visualization
# BTech Computer Science Stream
# Week 3: Numpy basics and vectorized computation
# Kenneth Francis Rodrigues, 240905112, 3/1/2025

In [2]:
import numpy as np

In [3]:
# Problem 1
# 1. Generate a 3x4 NumPy array with random integers between 1 
# and 50.   
# a. Calculate and print the Mean, Median, and Standard Deviation 
# of the array 
# b. Print the Sum of all elements and the sum of each row. 
# c. Reshape the 3x4 array into a 2x6 array and print it. 

arr = np.random.randint(1,50,(3,4))
print('Array:\n',arr)
print('mean: ',np.mean(arr))
print('median: ',np.median(arr))
print('standard deviation: ',np.std(arr))
print('sum of all elements: ',np.sum(arr))
print('row-wise sum: ',np.sum(arr,axis=1))
arr = np.reshape(arr,(2,6))
print('After reshaping:')
print(arr)

Array:
 [[41  4  3 39]
 [36 46 27 17]
 [18 19 31 12]]
mean:  24.416666666666668
median:  23.0
standard deviation:  13.823038337821714
sum of all elements:  293
row-wise sum:  [ 87 126  80]
After reshaping:
[[41  4  3 39 36 46]
 [27 17 18 19 31 12]]


In [4]:
# Problem 2
# 2. Create two (3 * 3) matrices using NumPy and print it. Perform 
# and print the results of the following linear algebra operations 
# a. Matrix addition 
# b. Matrix subtraction 
# c. Matrix multiplication (element-wise and dot product) 
# d. Transpose of a matrix 
# e. Determinant and inverse (if applicable) 

arr1 = np.random.randint(0,100,(3,3))
arr2 = np.random.randint(0,100,(3,3))
print('Array 1: \n',arr1)
print('Array 2: \n',arr2)

arradd = arr1 + arr2
print('After Adding:\n',arradd)

arrsub = arr1 - arr2
print('After Subtracting:\n',arrsub)

arrmul = np.dot(arr1,arr2)
print('After Multiplication:\n',arrmul)

print('Array 1 Transpose:\n',arr1.T)
print('Array 2 Transpose:\n',arr2.T)

det1 = np.linalg.det(arr1)
det2 = np.linalg.det(arr2)

print('Determinant of array 1: ',det1)
print('Determinant of array 2: ',det2)

if det1 != 0:
    inv1 = np.linalg.inv(arr1)
    print('Inverse of array 1:\n',inv1)
    
if det2 != 0:
    inv2 = np.linalg.inv(arr2)
    print('Inverse of array 1:\n',inv2)

Array 1: 
 [[75 31 40]
 [26 16 40]
 [22  2 28]]
Array 2: 
 [[79 90 81]
 [ 1 50 18]
 [23 17 80]]
After Adding:
 [[154 121 121]
 [ 27  66  58]
 [ 45  19 108]]
After Subtracting:
 [[ -4 -59 -41]
 [ 25 -34  22]
 [ -1 -15 -52]]
After Multiplication:
 [[6876 8980 9833]
 [2990 3820 5594]
 [2384 2556 4058]]
Array 1 Transpose:
 [[75 26 22]
 [31 16  2]
 [40 40 28]]
Array 2 Transpose:
 [[79  1 23]
 [90 50 17]
 [81 18 80]]
Determinant of array 1:  20312.000000000022
Determinant of array 2:  230112.99999999997
Inverse of array 1:
 [[ 0.01811737 -0.0387948   0.02953919]
 [ 0.00748326  0.06006302 -0.09649468]
 [-0.01476959  0.02619141  0.0193974 ]]
Inverse of array 1:
 [[ 0.01605298 -0.02530496 -0.01056003]
 [ 0.00145146  0.01936874 -0.00582757]
 [-0.00492367  0.00315932  0.01677437]]


In [5]:
def magic_check(mat):
    nums_used = []
    for i in range(len(mat)):
        for j in range(len(mat)):
            if a[i][j] not in nums_used:
                nums_used.append(a[i][j])
            else:
                return False
    rowsums = [sum(x) for x in mat]
    for i in range(1,len(rowsums)):
        if rowsums[i] != rowsums[0]:
            return False
    colsums = [0]*len(mat)
    for i in range(mat):
        for j in range(mat):
            colsums[j] += mat[i][j]
    for i in range(1,len(colsums)):
        if colsums[i] != colsums[0]:
            return False
    if colsums[0]!=rowsums[0]:
        return False
    diagsum1 = 0
    diagsum2 = 0
    for i in range(len(mat)):
        diagsum1 += mat[i][i]
        diagsum2 += mat[i][len(mat)-i-1]
    if diagsum1 != diagsum2:
        return False
    if diagsum1 != rowsums[0]:
        return False
    return True